feat(@vtmn/svelte): add `VtmnChip` component
Decathlon/vitamin-web pull request #1017
Opened 2022-03-04 18:08 UTC by Tlahey

Create a svelte `VtmnChip` component.

Some check need to do on this component : 
- Need to make some doc (variants cannot use all attributes on the same time, need to specify which can be use with others)

2022-03-08 13:49 UTC, GaspardMathon requested changes

2022-03-08 13:49 UTC, GaspardMathon commented on packages/sources/svelte/src/components/selection-controls/VtmnChip/VtmnChip.svelte
> +  @import '@vtmn/css-chips';
I think it is `@vtmn/css-chip`

2022-03-08 16:56 UTC, Tlahey commented on packages/sources/svelte/src/components/selection-controls/VtmnChip/VtmnChip.svelte
> +  @import '@vtmn/css-chips';
Ho yes ! Sorry xD

2022-03-08 19:05 UTC, Tlahey commented
I have a question though.
Wouldn't it be better to make X components Chip for each variant. So, each one has the necessary props and would not share props not useful for the variant 🤔 

For example, only chip filter can have a badge, so if we create a `VtmnChipFilter` it's more clear to see props used by the component

In counterpart, we have more component to maintains, but it's more clear ... To discuss.

2022-03-09 14:10 UTC, lauthieb requested changes
Thanks a lot @Tlahey, small changes :)

2022-03-09 14:10 UTC, lauthieb commented on packages/sources/svelte/src/components/selection-controls/VtmnChip/enums.js
> +export const VARIANTS = {
=> `VTMN_CHIP_VARIANT`

Same for size :)

2022-03-09 14:11 UTC, lauthieb commented
+ please delete `package-lock.json` as we only use yarn.

2022-03-09 15:10 UTC, lauthieb commented
@Tlahey I understand your proposition but we need to be as near as possible from the documentation and Figma, that's why I prefer only one component, even if some variants cannot be present together... Thanks for your understanding

2022-03-09 16:45 UTC, lauthieb approved these changes
Thanks a lot @Tlahey :)

2022-03-09 16:45 UTC, merged