feat(@vtmn/react): add VtmnProgressBar component
Decathlon/vitamin-web pull request #1018
Opened 2022-03-04 21:19 UTC by 0x2A-git

## Changes description

This P.R aims to add the VtmnProgressBar component

## Context

Related issue #491 

## Checklist

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch**. Please, don't request directly from your main!
- [x] Check commits & PR names matches our requested structure. It must follow the https://www.conventionalcommits.org pattern.
- [x] Check your code additions will fail neither code linting checks.
- [x] I have reviewed the submitted code.
- [x] I have tested on related showcases.
- [ ] If it includes design changes, please ask for a review with a core team designer.

## Does this introduce a breaking change?

- No

2022-03-05 21:35 UTC, lauthieb requested changes
Hi Lucas,
Thansk a lot for your contribution!!
I've made small changes, for me it's ok until one thing. It is buggy when circular & indeterminate:
![CleanShot 2022-03-05 at 22 35 22](https://user-images.githubusercontent.com/9600228/156900559-79bbf1fa-e09c-4d5c-b7a0-19eec58a0e61.gif)

2022-03-05 22:22 UTC, 0x2A-git commented
> Hi Lucas, Thansk a lot for your contribution!! I've made small changes, for me it's ok until one thing. It is buggy when circular & indeterminate: ![CleanShot 2022-03-05 at 22 35 22](https://user-images.githubusercontent.com/9600228/156900559-79bbf1fa-e09c-4d5c-b7a0-19eec58a0e61.gif)

Hi Laurent,

Thanks for the feedback, I'm not sure if I'm missing something or if it is an issue related to the CSS implementation. 

I've tried to reproduce the storybook story ( https://decathlon.github.io/vitamin-web/@vtmn/showcase-css/?path=/story/components-indicators-progressbar--circular ) and it seems like the circular progress bar with the indeterminate status does not match de one displayed on the website ( https://www.decathlon.design/726f8c765/p/2388f2-progressbar/b/42a1a2 )

2022-03-06 21:14 UTC, lauthieb approved these changes

2022-03-06 21:15 UTC, lauthieb commented
@0x2A-git you're completely right, I will make an issue for `@vtmn/css`!
Thanks again for your contribution!!

2022-03-06 21:15 UTC, merged