feat(@vtmn/svelte): add `VtmnButton` component
Decathlon/vitamin-web pull request #1024
Opened 2022-03-07 20:11 UTC by Tlahey

WIP

Need more informations on the modal functionalities

2022-03-09 08:50 UTC, Tlahey commented
Need to tests if we can initialize the modal on the body for all the application

2022-03-09 08:50 UTC, Tlahey commented on packages/showcases/svelte/stories/components/overlays/VtmnModal/VtmnModal.stories.svelte
> +    visible: {
show instead visible

2022-03-09 08:50 UTC, Tlahey commented on packages/sources/svelte/src/components/overlays/VtmnModal/VtmnModal.svelte
> +  export let visible = false;
show instead visible

2022-03-11 19:00 UTC, Tlahey commented
So ... I do some changes on the component.
- Add `disableAnimation`, why ? See this one 
-- With class `show` on the modal 
![image](https://user-images.githubusercontent.com/2856778/157933990-ad06c944-b77a-4617-b821-e56108e01d56.png)
-- Wihout class `show` on the modal
![image](https://user-images.githubusercontent.com/2856778/157934051-b3fadacd-0313-497b-8e57-5380ba6cdf3b.png)

So, animation will infect the z-index.

Another very interesting addition only on svelte : 
- Add automatically a `<style>` to hide the overflow on body when the modal is open ! 🔥

2022-03-15 10:11 UTC, lauthieb requested changes
Thanks a lot @Tlahey 

I have two remarks:
- It seems the control for showing the modal doesn't work on Storybook
- Can you please add "show = false" when we click on the buttons inside your example modal?

Thanks in advance :)

2022-03-15 13:27 UTC, Tlahey commented
> * when we click on the buttons inside your example modal?

I've tried to do some changes on the story, but args are only one way binding. Storybook don't handle to change this values on the documentation.

2022-03-15 17:37 UTC, lauthieb approved these changes
Awesome @Tlahey :)

2022-03-15 17:37 UTC, merged