feat(@vtmn/svelte): add VtmnAccordion component
Decathlon/vitamin-web pull request #1026
Opened 2022-03-08 10:55 UTC by yhafidi

## Changes description

## Context

## Checklist

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch**. Please, don't request directly from your main!
- [ ] Check commits & PR names matches our requested structure. It must follow the https://www.conventionalcommits.org pattern.
- [ ] Check your code additions will fail neither code linting checks.
- [ ] I have reviewed the submitted code.
- [ ] I have tested on related showcases.
- [ ] If it includes design changes, please ask for a review with a core team designer.

## Does this introduce a breaking change?

- Yes
- No

## Other information

2022-03-08 10:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Decathlon/vitamin-web?pullRequest=1026) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Decathlon/vitamin-web?pullRequest=1026) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Decathlon/vitamin-web?pullRequest=1026) it.</sub>

2022-03-08 13:53 UTC, GaspardMathon approved these changes

2022-03-08 15:22 UTC, GaspardMathon requested changes

2022-03-08 15:22 UTC, GaspardMathon commented on packages/sources/svelte/src/components/structure/VtmnAccordion/VtmnAccordion.svelte
> +   * @type {boolen} Display left icon on summary.
```suggestion
   * @type {boolean} Display left icon on summary.
```

2022-03-08 15:27 UTC, GaspardMathon commented
I tested the accordion, nice development overall just a few things to improve : 

- It would be better if the first item of the accordion was expanded (property `open` of the `details` tag.
- In the controls, you should be able to trigger the boolean to display the icon or not.
- Same for the `disabled` property
- Same for the summary, If a enter a custom text it has to replace the current summary of the accordion

For the 3 last changes, It's ok not to have them if the Two first stories with multiple items in the accordion but for the single accordion at least.

Thanks for your contribution 💯

2022-03-08 21:46 UTC, Tlahey commented on packages/showcases/svelte/stories/components/structure/VtmnAccordion/VtmnAccordion.stories.svelte
> +  }
@yhafidi my bad, this one apply on all the components, we need to wrap it with another solution

2022-03-09 15:22 UTC, GaspardMathon submitted a review, later dismissed

2022-03-10 14:23 UTC, GaspardMathon approved these changes

2022-03-11 10:12 UTC, lauthieb requested changes
Thanks a lot @yhafidi, just small changes :)

2022-03-11 10:12 UTC, lauthieb commented on packages/sources/svelte/rollup.config.js
> +      components: ['VtmnDivider', 'VtmnList', 'VtmnListItem', 'VtmnAccordion'],
```suggestion
      components: ['VtmnAccordion', 'VtmnDivider', 'VtmnList', 'VtmnListItem'],
```

2022-03-11 10:12 UTC, lauthieb commented on packages/sources/svelte/src/components/index.js
>  export { default as VtmnListItem } from './structure/VtmnListItem/VtmnListItem.svelte';
```suggestion
export { default as VtmnAccordion } from './structure/VtmnAccordion/VtmnAccordion.svelte';
export { default as VtmnDivider } from './structure/VtmnDivider/VtmnDivider.svelte';
export { default as VtmnList } from './structure/VtmnList/VtmnList.svelte';
export { default as VtmnListItem } from './structure/VtmnListItem/VtmnListItem.svelte';
```

2022-03-11 10:12 UTC, lauthieb commented on packages/sources/svelte/src/components/structure/VtmnAccordion/VtmnAccordion.svelte
> +<details class={componentClass} aria-disabled={disabled} {open}>
I think you don't need to specify "open" prop as it's an HTML default property.
But if we want to set it, you will need to spread `$$restProps` to the `<details>` HTML block.

2022-03-11 10:12 UTC, lauthieb commented on packages/showcases/svelte/stories/components/structure/VtmnAccordion/VtmnAccordion.stories.svelte
> +  const argTypes = {
Should be moved in `@vtmn/showcase-core/csf/components/structure/accordion.csf` as we did with other files.

2022-03-11 13:35 UTC, lauthieb approved these changes

2022-03-11 13:54 UTC, GaspardMathon approved these changes

2022-03-11 14:06 UTC, merged