feat(@vtmn/svelte): add `VtmnCard` component
Decathlon/vitamin-web pull request #1028
Opened 2022-03-08 14:52 UTC by Tlahey

Add a VtmnCard component

2022-03-08 15:44 UTC, GaspardMathon commented
You missed on variant for the full-image : The overlay can be a gradient or a single color opacity : 
![image](https://user-images.githubusercontent.com/26525340/157272709-377ceaf6-512c-4c13-a66d-3de5c78dfbce.png)

2022-03-08 15:44 UTC, GaspardMathon commented
Overall it seems to work very well :) Thanks a lot

2022-03-09 15:05 UTC, Tlahey commented on packages/sources/svelte/src/components/structure/VtmnCard/VtmnCard.svelte
> +      <img src={img} alt="" />
Use a slot instead a props ? 🤔

2022-03-09 22:02 UTC, Tlahey commented
Ready to review and merge 🚀  !

2022-03-11 10:32 UTC, GaspardMathon requested changes

2022-03-11 10:32 UTC, GaspardMathon commented on packages/showcases/svelte/stories/components/structure/VtmnCard/VtmnCard.stories.svelte
> +  };
You should try to put the args of the component inside the .csf file to share the args with all libraries.

2022-03-11 15:34 UTC, GaspardMathon approved these changes

2022-03-15 10:05 UTC, lauthieb approved these changes
Thanks a lot!!

2022-03-15 10:06 UTC, merged