feat(@vtmn/react): add `VtmnSearch` component
Decathlon/vitamin-web pull request #1031
Opened 2022-03-09 19:49 UTC by 0x2A-git

## Changes description

This P.R adds the search component along with its showcase

## Context

Related issue #821 

## Checklist

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch**. Please, don't request directly from your main!
- [x] Check commits & PR names matches our requested structure. It must follow the https://www.conventionalcommits.org pattern.
- [x] Check your code additions will fail neither code linting checks.
- [x] I have reviewed the submitted code.
- [x] I have tested on related showcases.
- [x] If it includes design changes, please ask for a review with a core team designer.

## Does this introduce a breaking change?

- No

## Other information

2022-03-15 09:03 UTC, lauthieb requested changes
Hi @0x2A-git thanks for your proposal! Just a few change for the moment before going deeper to your PR :)

2022-03-15 09:03 UTC, lauthieb commented on packages/sources/react/src/index.ts
> +export type { VtmnSearchProps } from './components/navigation/search/VtmnSearch';
Can you please rename the "search" folder to "VtmnSearch" as we did with other components please? :)

2022-03-18 15:26 UTC, lauthieb commented
I convert to draft, can you please fix conflicts @0x2A-git ? :)

2022-03-18 15:26 UTC, lauthieb commented
I convert to draft, can you please fix conflicts @0x2A-git ? :)

2022-03-18 17:45 UTC, 0x2A-git commented
> I convert to draft, can you please fix conflicts @0x2A-git ? :)

It's done :), thanks for the report I didn't notice it :woozy_face:

2022-03-21 09:45 UTC, lauthieb approved these changes
Thanks a lot! :)

2022-03-21 09:45 UTC, merged