feat(@vtmn/svelte): add `VtmnSnackbar` component
Decathlon/vitamin-web pull request #1041
Opened 2022-03-11 23:37 UTC by Tlahey

Add `VtmnSnackbar` component for svelte
<img width="681" alt="image" src="https://user-images.githubusercontent.com/2856778/157989437-23ac74d6-e850-4e05-8af5-057e55322659.png">

2022-03-12 09:25 UTC, Tlahey commented on packages/sources/svelte/src/components/overlays/VtmnSnackbar/VtmnSnackbar.svelte
> +        show = false;
clearTimeout

2022-03-12 09:37 UTC, Tlahey commented on packages/sources/svelte/src/components/overlays/VtmnSnackbar/VtmnSnackbar.svelte
> +  export let displayCloseButton = false;
Rename by `withCloseButton`

2022-03-13 14:52 UTC, Tlahey commented on packages/showcases/core/csf/components/overlays/snackbar.csf.js
> +    description: 'Text display on the snackbar',
`Text displayed on the snackbar`

2022-03-13 14:53 UTC, Tlahey commented on packages/showcases/svelte/stories/components/overlays/VtmnSnackbar/VtmnSnackbar.stories.svelte
> +      console.log('Display snackbar');
Remove

2022-03-13 14:54 UTC, Tlahey commented on packages/sources/svelte/src/components/overlays/VtmnSnackbar/README.md
> +First, you need to place the `VtmnSnackbar` component preferably at your
First, you need to place the `VtmnSnackbar` component on the top of your application

2022-03-13 14:54 UTC, Tlahey commented on packages/sources/svelte/src/components/overlays/VtmnSnackbar/README.md
> +First, you need to place the `VtmnSnackbar` component preferably at your
First, you need to place the `VtmnSnackbar` component on the top of your application

2022-03-13 14:55 UTC, Tlahey commented on packages/sources/svelte/src/components/overlays/VtmnSnackbar/README.md
> +You need to add `@vtmn/svelte` on your `package.json`
+ `@vtmn/icon`

2022-03-15 10:45 UTC, lauthieb requested changes
Thanks @Tlahey.

Just a question, I see that we can change the actionLabel, but it is possible to interact with this button? I mean add a `onclick` trigger if we click on this action button inside the snackbar?

Thanks.

2022-03-15 14:15 UTC, jb-thery approved these changes
Nice job !

2022-03-15 17:39 UTC, lauthieb approved these changes
big up @Tlahey :)

2022-03-15 17:39 UTC, merged