feat(@vtmn/svelte): create `VtmnToast` component
Decathlon/vitamin-web pull request #1042
Opened 2022-03-13 11:09 UTC by Tlahey

Create a `VtmnToast` component for svelte.

How it works : 
- `VtmnToast` need to be put on the main body of the application.
- `VtmnToastItem` are used by the `VtmnToast` to display toasts
- A store `vtmnToastStore` can be imported everywhere on the application, you can use the function `vtmnToastStore.send({ content: 'Hello world!' })` to send toast to diplay

2022-03-13 14:48 UTC, Tlahey commented on packages/showcases/core/csf/components/overlays/toast.csf.js
> +    description: 'Text display on the toast',
displayed

2022-03-13 14:50 UTC, Tlahey commented on packages/sources/svelte/src/components/overlays/VtmnToast/VtmnToastItem.svelte
> +   * @type {string} display a close button on right
Just `display a close button`

2022-03-13 14:51 UTC, Tlahey commented on packages/sources/svelte/src/components/overlays/VtmnToast/VtmnToastItem.svelte
> +   * @type {number} timeout before the component execute the close action
`Time before the component dispatch automatically 'close'`

2022-03-13 14:52 UTC, Tlahey commented on packages/sources/svelte/src/components/overlays/VtmnToast/vtmnToastStore.js
> +    return this._id;
`return ++this._id`

2022-03-13 14:54 UTC, Tlahey commented on packages/sources/svelte/src/components/overlays/VtmnToast/README.md
> +First, you need to place the `VtmnToast` component preferably at your
First, you need to place the `VtmnToast` component on the top of your application

2022-03-13 14:56 UTC, Tlahey commented on packages/sources/svelte/src/components/overlays/VtmnToast/README.md
> +You need to add `@vtmn/svelte` on your `package.json`
+ `@vtmn/icon`

2022-03-13 14:58 UTC, Tlahey commented on packages/sources/svelte/src/components/overlays/VtmnToast/test/vtmnToastItem.spec.js
> +  test('Should display the content of the toast', () => {
Add test `Should apply custom class to toast`

2022-03-13 15:01 UTC, Tlahey commented on packages/sources/svelte/src/components/overlays/VtmnToast/VtmnToastItem.svelte
> +   */
@defaultValue 'false'

2022-03-13 15:01 UTC, Tlahey commented on packages/sources/svelte/src/components/overlays/VtmnToast/VtmnToastItem.svelte
> +   */
@defaultValue 'false'

2022-03-14 15:30 UTC, Tlahey commented on packages/sources/svelte/src/components/overlays/VtmnToast/VtmnToastItem.svelte
> +  const closeHandler = () => {
```
const closeHandler = () => dispatch('close');
```

2022-03-14 16:50 UTC, Tlahey commented on packages/sources/svelte/src/components/overlays/VtmnToast/test/vtmnToastItem.spec.js
> +  const expectedCancelOnElement = async (
`expectedCloseOnElement`

2022-03-15 10:47 UTC, lauthieb requested changes
Thanks @Tlahey for this contribution.

Do you please know why the toast is not centered? 

![CleanShot 2022-03-15 at 11 47 02](https://user-images.githubusercontent.com/9600228/158361420-8605f908-03fe-4a27-ae14-d3861c279e26.png)

2022-03-15 10:48 UTC, lauthieb requested changes

2022-03-15 10:48 UTC, lauthieb commented on packages/sources/svelte/src/components/overlays/VtmnToast/test/vtmnToastItem.spec.js
> +  const expectedCancelOnElement = async (
@Tlahey ?

2022-03-15 17:44 UTC, lauthieb requested changes
Thanks @Tlahey for your contribution.

Do you know why the toast is not centered please? 

Thanks!

![CleanShot 2022-03-15 at 18 43 39](https://user-images.githubusercontent.com/9600228/158439195-87272ffe-654b-4d7c-a478-67960dbf2aa2.png)

2022-03-15 19:57 UTC, Tlahey commented
> Thanks @Tlahey for your contribution.
> 
> Do you know why the toast is not centered please?
> 
> Thanks!
> 
> ![CleanShot 2022-03-15 at 18 43 39](https://user-images.githubusercontent.com/9600228/158439195-87272ffe-654b-4d7c-a478-67960dbf2aa2.png)

The toast is centered on all the page, not the preview (class show)

<img width="628" alt="image" src="https://user-images.githubusercontent.com/2856778/158460564-a17c592c-92bf-43a0-ac7e-13ac42cff1e9.png">

On this case, if we remove the right:50%, the toast are correctly align center into the container.

2022-03-15 20:16 UTC, Tlahey commented
It's ok ! I don't know why but the `$$restProp` have been deleted. My bad, it's fixed :)

2022-03-16 08:05 UTC, lauthieb approved these changes
Thanks for you work @Tlahey 💪

2022-03-16 08:05 UTC, merged