feat(@vtmn/svelte): add VtmnLoader component
Decathlon/vitamin-web pull request #1053
Opened 2022-03-20 22:39 UTC by Tlahey

WIP

2022-03-21 10:35 UTC, Tlahey commented on packages/showcases/core/csf/components/indicators/loader.csf.js
> +  },
Change to `progress.csf`

2022-03-21 10:36 UTC, Tlahey commented on packages/showcases/svelte/stories/components/indicators/VtmnLoader/VtmnLoader.stories.svelte
> +<script>
`VtmnProgressbar`

2022-03-21 10:36 UTC, Tlahey commented on packages/sources/svelte/package.json
> +    "@vtmn/css-loader": "^0.2.23",
`@vtmn/css-progressbar`

2022-03-21 10:36 UTC, Tlahey commented on packages/sources/svelte/rollup.config.js
> +        'VtmnLoader',
`VtmnProgressbar`

2022-03-21 10:36 UTC, Tlahey commented on packages/sources/svelte/src/components/index.js
> +export { default as VtmnLoader } from './indicators/VtmnLoader/VtmnLoader.svelte';
`export { default as VtmnProgressbar } from './indicators/VtmnProgressbar/VtmnProgressbar.svelte`

2022-03-21 10:37 UTC, Tlahey commented on packages/sources/svelte/src/components/indicators/VtmnLoader/VtmnLoader.svelte
> +<script>
move to `VtmnProgressbar.svelte`

2022-03-23 10:41 UTC, lauthieb requested changes

2022-03-23 10:41 UTC, lauthieb commented on packages/showcases/core/csf/components/indicators/loader.csf.js
> -};
Why?

2022-03-23 10:41 UTC, lauthieb commented on packages/sources/svelte/src/components/indicators/VtmnProgressbar/enums.js
> +};
Should be prefixed by `VTMN_PROGRESSBAR` instead of `VTMN_LOADER`

2022-03-23 10:50 UTC, GaspardMathon commented on packages/sources/svelte/src/components/indicators/VtmnProgressbar/README.md
> +First, you need to place the `VtmnAlert` component on the top of your application
```suggestion
First, you need to place the `VtmnProgressbar` component on the top of your application
```

2022-03-23 13:12 UTC, Tlahey commented on packages/showcases/core/csf/components/indicators/loader.csf.js
> -};
Yes missing delete on my side, I rollback

2022-03-24 13:25 UTC, GaspardMathon submitted a review, later dismissed

2022-03-24 22:01 UTC, merged