feat(@vtmn/svelte): add `VtmnSelect` component
Decathlon/vitamin-web pull request #1065
Opened 2022-03-23 13:08 UTC by Tlahey

Create a new `VtmnSelect` component for svelte.

![image](https://user-images.githubusercontent.com/2856778/159706532-bd060dd8-ab69-43c4-9589-6471cf2bd851.png)

2022-03-23 13:40 UTC, lauthieb requested changes
Thanks @Tlahey, just few changes ;)

2022-03-23 14:26 UTC, Tlahey commented on packages/showcases/svelte/stories/components/forms/VtmnSelect/select.csf.js
> +export const argTypes = {
The `csf` core file are already used by others components but have some unused properties like `error` and `errorText`.
If we have an error, it should display the error. We didn't need to apply another property to show / hide this one.

For `labelText` it is not necessary to have sufix `Text`, the type of the element is `string`

We includes others properties like : 
- name
- autocomplete
- value (2 way for the binding)

2022-03-24 13:16 UTC, GaspardMathon approved these changes

2022-03-24 22:12 UTC, lauthieb approved these changes
Thanks a lot @Tlahey :)

2022-03-24 22:12 UTC, merged