feat(@vtmn/svelte): add `search` component
Decathlon/vitamin-web pull request #1078
Opened 2022-03-28 09:24 UTC by GaspardMathon

## Changes description

- Add `search` component

## Context

## Checklist

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch**. Please, don't request directly from your main!
- [ ] Check commits & PR names matches our requested structure. It must follow the https://www.conventionalcommits.org pattern.
- [ ] Check your code additions will fail neither code linting checks.
- [ ] I have reviewed the submitted code.
- [ ] I have tested on related showcases.
- [ ] If it includes design changes, please ask for a review with a core team designer.

## Does this introduce a breaking change?

- No

2022-03-29 20:06 UTC, ThomasLaigneauDecathlon commented on packages/sources/vue/src/components/navigation/VtmnSearch/VtmnSearch.vue
> +        v-bind="$attrs"
Il ne faut pas utiliser v-bind="$attrs" sur plusieurs éléments html différents.
Ici on veut uniquement faire passer des attributs sur l'input.

2022-03-29 20:06 UTC, ThomasLaigneauDecathlon commented on packages/sources/vue/src/components/navigation/VtmnSearch/VtmnSearch.vue
> +        v-bind="$attrs"
Il ne faut pas utiliser v-bind="$attrs" sur plusieurs éléments html différents.
Ici on veut uniquement faire passer des attributs sur l'input.

2022-03-29 20:07 UTC, ThomasLaigneauDecathlon commented on packages/sources/vue/src/components/navigation/VtmnSearch/VtmnSearch.vue
> +      :placeholder="placeholder"
Tu peux ajouter :value="modelValue" ici pour bien mettre en place le double binding du v-model

2022-04-04 19:13 UTC, lauthieb requested changes

2022-04-04 19:13 UTC, lauthieb commented on packages/sources/vue/src/components/navigation/VtmnSearch/VtmnSearch.vue
> +        @click.prevent="handleSearch"
Can you please use "onSearch" instead of "searchCallback" as we did in `VtmnSearch` svelte component?

2022-04-04 20:18 UTC, ThomasLaigneauDecathlon requested changes
With and emitted event instead of a callback function the minimum setup for the component will be : 

`<VtmnSearch v-model="searchValue" @search="triggerSearch($event)" />`

2022-04-04 20:18 UTC, ThomasLaigneauDecathlon commented on packages/sources/vue/src/components/navigation/VtmnSearch/VtmnSearch.vue
> +    searchCallback: {
We can remove this props and avoid to pass a callback function by using instead an emitted event 'search'.

What do you think about it ? It make the component more "stateless".

2022-04-04 20:18 UTC, ThomasLaigneauDecathlon commented on packages/sources/vue/src/components/navigation/VtmnSearch/VtmnSearch.vue
> +  emits: ['update:modelValue'],
```suggestion
  emits: ['update:modelValue', 'search'],
```

2022-04-04 20:18 UTC, ThomasLaigneauDecathlon commented on packages/sources/vue/src/components/navigation/VtmnSearch/VtmnSearch.vue
> +        iconAlone="search-line"
```suggestion
        icon-alone="search-line"
```

2022-04-04 20:18 UTC, ThomasLaigneauDecathlon commented on packages/sources/vue/src/components/navigation/VtmnSearch/VtmnSearch.vue
> +        iconAlone="close-line"
```suggestion
        icon-alone="close-line"
```

2022-04-05 18:29 UTC, lauthieb approved these changes
Thanks a lot @GaspardMathon :)

2022-04-05 18:31 UTC, lauthieb commented
@ThomasLaigneauDecathlon feel free to check again because @GaspardMathon resolved your remarks :)

2022-04-06 19:20 UTC, ThomasLaigneauDecathlon approved these changes

2022-04-07 08:46 UTC, merged