feat(@vtmn/vue): add `VtmnSnackbar` component
Decathlon/vitamin-web pull request #1107
Opened 2022-04-04 13:25 UTC by GaspardMathon

## Changes description

- add `VtmnSnackbar` component

## Context

## Checklist

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch**. Please, don't request directly from your main!
- [ ] Check commits & PR names matches our requested structure. It must follow the https://www.conventionalcommits.org pattern.
- [ ] Check your code additions will fail neither code linting checks.
- [ ] I have reviewed the submitted code.
- [ ] I have tested on related showcases.
- [ ] If it includes design changes, please ask for a review with a core team designer.

## Does this introduce a breaking change?

- No

2022-04-04 15:41 UTC, lauthieb requested changes

2022-04-04 15:41 UTC, lauthieb commented on packages/showcases/core/csf/components/overlays/snackbar.csf.js
> -    defaultValue: 'Action',
Why?

2022-04-04 19:17 UTC, lauthieb requested changes

2022-04-04 19:17 UTC, lauthieb commented on packages/sources/vue/src/components/overlays/VtmnSnackbar/VtmnSnackbar.vue
> +    },
Can you please use "onClose" and "onAction" as we did with `VtmnSnackbar` svelte component?

2022-04-05 18:35 UTC, lauthieb submitted a review, later dismissed

2022-04-06 19:30 UTC, ThomasLaigneauDecathlon commented on packages/sources/vue/src/components/overlays/VtmnSnackbar/VtmnSnackbar.vue
> +        show: true,
```suggestion
        'show': true,
```

2022-04-07 08:53 UTC, merged