refactor(@vtmn/svelte): optimization `VtmnModal`
Decathlon/vitamin-web pull request #1111
Opened 2022-04-05 10:00 UTC by GaspardMathon

## Changes description

- Optimisation of slots
- Title is now a slot
- Slots don't include parent class

## Context

## Checklist

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch**. Please, don't request directly from your main!
- [ ] Check commits & PR names matches our requested structure. It must follow the https://www.conventionalcommits.org pattern.
- [ ] Check your code additions will fail neither code linting checks.
- [ ] I have reviewed the submitted code.
- [ ] I have tested on related showcases.
- [ ] If it includes design changes, please ask for a review with a core team designer.

## Does this introduce a breaking change?

- Yes, Change the title prop into a slot

2022-04-05 10:02 UTC, Tlahey commented on packages/showcases/svelte/stories/components/overlays/VtmnModal/VtmnModal.stories.svelte
> +    <slot slot="title">This is the title</slot>
```
<svelte:fragment slot="title">
This is the title
</svelte:fragment>
````

2022-04-05 10:02 UTC, Tlahey commented on packages/showcases/svelte/stories/components/overlays/VtmnModal/VtmnModal.stories.svelte
> +    <slot slot="description">
```
<svelte:fragment slot="description">
This is the title
</svelte:fragment>
```

2022-04-05 10:08 UTC, Tlahey commented on packages/showcases/svelte/stories/components/overlays/VtmnModal/VtmnModal.stories.svelte
> +    <slot slot="actions">
```
<svelte:fragment slot="actions">
[...]
</svelte:fragment>
```

2022-04-05 10:08 UTC, Tlahey commented on packages/showcases/svelte/stories/components/overlays/VtmnModal/VtmnModal.stories.svelte
> +    <slot slot="title">This is the title</slot>
```
<svelte:fragment slot="title">
[...]
</svelte:fragment>
```

2022-04-05 10:08 UTC, Tlahey commented on packages/showcases/svelte/stories/components/overlays/VtmnModal/VtmnModal.stories.svelte
> +    <slot slot="description">
```
<svelte:fragment slot="description">
[...]
</svelte:fragment>
```

2022-04-05 10:08 UTC, Tlahey commented on packages/sources/svelte/src/components/overlays/VtmnModal/test/VtmnModal.spec.js
> +        title: 'Unit-test',
No more props `title`

2022-04-05 10:08 UTC, Tlahey commented on packages/sources/svelte/src/components/overlays/VtmnModal/test/VtmnModal.spec.js
> +          title: 'Unit-test',
No more props `title`

2022-04-05 10:08 UTC, Tlahey commented on packages/sources/svelte/src/components/overlays/VtmnModal/test/VtmnModalWithSlots.svelte
>    <p slot="description">description</p>
use `<svelte:fragment>`

2022-04-05 10:08 UTC, Tlahey commented on packages/sources/svelte/src/components/overlays/VtmnModal/test/VtmnModalWithDescription.svelte
>    <p slot="description">description</p>
use `<svelte:fragment>`

2022-04-05 10:08 UTC, Tlahey commented on packages/sources/svelte/src/components/overlays/VtmnModal/test/VtmnModal.spec.js
> +    });
Check if slot have class `vtmn-modal_content_title--text`

2022-04-05 12:20 UTC, GaspardMathon reviewed
Thanks @Tlahey  :)

2022-04-05 18:25 UTC, lauthieb requested changes
This causes problem with existing modal in React.
Let's check this together in videoconference tomorrow. :)

2022-04-06 15:03 UTC, lauthieb approved these changes

2022-04-06 15:30 UTC, Tlahey approved these changes

2022-04-06 15:30 UTC, lauthieb approved these changes

2022-04-06 15:35 UTC, merged