feat(@vtmn/svelte): add `VtmnDropdown` component
Decathlon/vitamin-web pull request #1112
Opened 2022-04-05 11:22 UTC by Tlahey

Refer to #1051

2022-04-05 12:26 UTC, GaspardMathon approved these changes

2022-04-05 12:26 UTC, GaspardMathon commented on packages/showcases/core/csf/components/actions/dropdown.csf.js
> +    description: 'Max height of menu, this enable scroll',
```suggestion
    description: 'Max height of menu, this enables scroll',
```

2022-04-05 15:03 UTC, Tlahey commented
Need to update code, refer A11y -> #1113

2022-04-05 18:38 UTC, lauthieb commented
> Need to update code, refer A11y -> #1113

What do you mean @Tlahey by this comment?

2022-04-06 07:09 UTC, lauthieb commented
@Tlahey thanks! Is it ok for you? If yes we will take this PR ready for review again :)

2022-04-06 08:18 UTC, Tlahey commented
@lauthieb yes it's good for me :)

2022-04-06 09:47 UTC, GaspardMathon submitted a review, later dismissed

2022-04-06 14:59 UTC, lauthieb requested changes
Thanks @Tlahey

2022-04-06 14:59 UTC, lauthieb commented on packages/showcases/core/csf/components/actions/dropdown.csf.js
> +  },
This intelligence should be placed on CSS part instead.

2022-04-06 15:07 UTC, lauthieb requested changes

2022-04-06 15:07 UTC, lauthieb commented on packages/showcases/svelte/stories/components/actions/VtmnDropdown/VtmnDropdown.stories.svelte
> +</Story>
Same here

2022-04-06 15:09 UTC, lauthieb requested changes

2022-04-06 15:09 UTC, lauthieb commented on packages/sources/svelte/src/components/actions/VtmnDropdownItem/VtmnDropdownItem.svelte
> +  export let checked = false;
should be renamed to "selected" has we did in design side.

2022-04-06 15:52 UTC, Tlahey commented
FYI : add max-height 260px to fit 5 items without scroll on the dropdown

2022-04-08 11:28 UTC, lauthieb approved these changes

2022-04-08 12:18 UTC, lauthieb commented
@jb-thery & @Tlahey , AWESOME!! Thanks :tada:

2022-04-08 12:18 UTC, merged