feat(@vtmn/react, @vtmn/vue): add `VtmnDropdown` component
Decathlon/vitamin-web pull request #1169
Opened 2022-05-30 16:05 UTC by GaspardMathon

## Changes description

## Context

## Checklist

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch**. Please, don't request directly from your main!
- [ ] Check commits & PR names matches our requested structure. It must follow the https://www.conventionalcommits.org pattern.
- [ ] Check your code additions will fail neither code linting checks.
- [ ] I have reviewed the submitted code.
- [ ] I have tested on related showcases.
- [ ] If it includes design changes, please ask for a review with a core team designer.

## Does this introduce a breaking change?

- No

2022-06-27 09:09 UTC, lauthieb requested changes

2022-06-28 12:08 UTC, GaspardMathon commented on packages/sources/react/src/components/actions/VtmnDropdown/VtmnDropdownItem.tsx
> +  const [checked, setChecked] = React.useState(false);
done

2022-06-28 13:00 UTC, lauthieb requested changes
Thanks @GaspardMathon.
For me it's ok for Vue implementation.
But there's a problem with React, details with the showcases below:

Svelte & Vue: OK ✅
![CleanShot 2022-06-28 at 14 56 58](https://user-images.githubusercontent.com/9600228/176184618-9a1e45cf-60c7-4bfd-b288-e6ec225e7db6.gif)
![CleanShot 2022-06-28 at 14 58 58](https://user-images.githubusercontent.com/9600228/176184631-0523071b-bef9-4dbb-b5a1-53f37e56f5fc.gif)

React : KO ❌

![CleanShot 2022-06-28 at 14 57 54](https://user-images.githubusercontent.com/9600228/176184669-fc9d2687-abf2-478f-9570-7bc4fed5198e.gif)

2022-06-28 15:19 UTC, lauthieb approved these changes

2022-06-28 15:20 UTC, merged