feat(@vtmn/react): adds boolean to disable VtmnTooltip when needed
Decathlon/vitamin-web pull request #1195
Opened 2022-06-24 12:15 UTC by MaelthiS

## Changes description
This PR adds a boolean isTooltipDisabled to the VtmnTooltip component to be able to disable or not the tooltip.
The boolean has a false value by default.

## Context
We needed this change in order to display or not the tooltip when a button is active or not.
https://github.com/Decathlon/vitamin-web/issues/1192

## Checklist

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch**. Please, don't request directly from your main!
- [ ] Check commits & PR names matches our requested structure. It must follow the https://www.conventionalcommits.org pattern.
- [ ] Check your code additions will fail neither code linting checks.
- [ ] I have reviewed the submitted code.
- [ ] I have tested on related showcases.
- [ ] If it includes design changes, please ask for a review with a core team designer.

## Does this introduce a breaking change?
- No

2022-06-24 12:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Decathlon/vitamin-web?pullRequest=1195) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Decathlon/vitamin-web?pullRequest=1195) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Decathlon/vitamin-web?pullRequest=1195) it.</sub>

2022-06-24 15:09 UTC, GaspardMathon requested changes
Made some suggestions to make your development more agnostic

2022-06-27 07:20 UTC, MaelthiS commented on packages/sources/react/src/components/overlays/VtmnTooltip/VtmnTooltip.tsx
> +      {isTooltipDisabled ? (
I made the changes, thanks for your feedback @GaspardMathon

2022-06-27 08:06 UTC, GaspardMathon requested changes

2022-06-27 08:06 UTC, GaspardMathon commented on packages/showcases/core/csf/components/overlays/tooltip.csf.js
> +    description: 'To disable the tooltip',
```suggestion
    description: 'Whether the tooltip is disabled',
```

2022-06-27 08:06 UTC, GaspardMathon commented on packages/sources/react/src/components/overlays/VtmnTooltip/VtmnTooltip.tsx
> +   * To Disable the Tooltip
```suggestion
   * Whether the tooltip is disabled
```

2022-06-27 11:11 UTC, lauthieb commented
Hi @MaelthiS,
Thanks for your proposition.
I have to close it thanks to my explanation here: https://github.com/Decathlon/vitamin-web/issues/1192#issuecomment-1167217698
Thanks for your understanding.

2022-06-27 11:11 UTC, closed without merging