feat(@vtmn/css, @vtmn/svelte, @vtmn/react, @vtmn/vue): add rel attribute for blank link targets to prevent security issues
Decathlon/vitamin-web pull request #1245
Opened 2022-08-25 15:02 UTC by GaspardMathon

## Changes description

- Add `rel="noopener noreferrer"` to every link with an explicit `target` value set to `_blank` to prevent security issues

## Context

- Close #1242 

## Checklist

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch**. Please, don't request directly from your main!
- [x] Check commits & PR names matches our requested structure. It must follow the https://www.conventionalcommits.org pattern.
- [x] Check your code additions will fail neither code linting checks.
- [x] I have reviewed the submitted code.
- [x] I have tested on related showcases.
- [x] If it includes design changes, please ask for a review with a core team designer.

## Does this introduce a breaking change?

- No

## Other information

Thanks @Tlahey for the issue 🔥

2022-08-25 19:34 UTC, lauthieb requested changes
Hi @GaspardMathon,

Thank you very much for this PR that corrects this security problem in our showcases. However, I don't think it completely fixes the issue raised by @Tlahey.

Indeed, we would also need to handle this automatically within our `VtmnLink` components on our different libraries `@vtmn/react`, `@vtmn/svelte` `& @vtmn/vue`. 
If `target='_blank``, then force the addition of `rel="noopener noreferrer"` inside its markup.

What do you think @GaspardMathon & @Tlahey?

Thanks :)

2022-08-26 08:20 UTC, Tlahey commented
Of course @lauthieb !
This security issue must be include inside the components :) 

if target = _blank and rel doesn't include noopener add noopener / rel doesn't include noreferrer add noreferrer

2022-08-26 13:16 UTC, thibault-mahe requested changes
Agreed with @lauthieb & @Tlahey on the `VtmnLink` needed change.
Thanks!

2022-09-13 06:57 UTC, Tlahey commented
@GaspardMathon I will provide the changes on the svelte part :)

2022-09-15 13:00 UTC, thibault-mahe requested changes

2022-09-15 13:00 UTC, thibault-mahe commented on packages/sources/react/src/components/actions/VtmnLink/VtmnLink.tsx
> +
I'm not sure that we should rewrite the whole (or part of the) HTML link standard API here:
- User should be able to use any legal HTML link attribute on our `VtmnLink`. User should just write attributes and this attributes should be on the rendered link ;
- Optional HTML link attribute should not be made mandatory for no reason in our `VtmnLink` (with maybe some accessibility exception).

Meaning that `target` and `rel`, that are already part of the link api, should not be a component props.
Instead we should maybe just "intercept" some native attribute to edit their values, when needed.

For instance :
```
export const VtmnLink = ({
   // no "rel" nor "target" props here 
  ...,
  // if user add native rel or target attributes, they will be stored in the following:
  ...props
}: VtmnLinkProps) => {

  // "Intercept" attributes to edit it
  const relAttrValues = Array.from(
    new Set([
      // If component has a given "rel" attribute, keep values
      ...(props?.rel?.split(' ') ?? []),
      // If comp has "target" set to "blank", add some values
      ...(props?.target === '_blank' ? ['noopener', 'noreferrer'] : []),
    ]),
  ).join(' ').trim();

  return (
    <a
      ...
      {...props}
      {...(relAttrValues ? { rel: relAttrValues } : {})}
    >
      ...
    </a>
  );
};
```

2022-09-23 12:14 UTC, thibault-mahe approved these changes

2022-10-07 07:43 UTC, thibault-mahe approved these changes

2022-10-12 07:23 UTC, lauthieb approved these changes

2022-10-12 12:38 UTC, lauthieb approved these changes

2022-10-12 12:39 UTC, lauthieb commented
@thibault-mahe for me that's ok.
If we are sure there's no breaking change, you can merge it directly. If there are breaking changes, please merge & inform all our consumers.
Thanks!

2022-10-17 07:22 UTC, merged