fix(@vtmn/svelte): add unit param on `VtmnSkeleton`
Decathlon/vitamin-web pull request #1252
Opened 2022-08-30 16:20 UTC by Tlahey

<img width="1291" alt="image" src="https://user-images.githubusercontent.com/2856778/187488995-da6b7927-34ea-47ed-99fb-28c7a71cb843.png">

2022-08-30 20:56 UTC, lauthieb commented on packages/sources/svelte/src/components/structure/VtmnSkeleton/test/vtmnSkeleton.spec.js
> +    const { container } = render(VtmnSkeleton, { unit: 'toto' });
```suggestion
    const { container } = render(VtmnSkeleton, { unit: 'foo' });
```

2022-08-31 07:07 UTC, Tlahey commented on packages/sources/svelte/src/components/structure/VtmnSkeleton/VtmnSkeleton.svelte
> +  $: computedWidth = width > 0 ? width : VTMN_DEFAULT_WIDTH;
Hello @lauthieb 
Yes, I hesitate between the 2 possibilities.

Why I choose width = 100, like browser, when you set an invalid value on width, it removed the width prop.
So, in fact, there are not set to 0 by default.

2022-09-01 08:38 UTC, lauthieb commented on packages/sources/svelte/src/components/structure/VtmnSkeleton/VtmnSkeleton.svelte
> +  $: computedWidth = width > 0 ? width : VTMN_DEFAULT_WIDTH;
Hi @Tlahey, I understand your point.
As `width: 0px` is correct, I prefer:
`$: computedWidth = width >= 0 ? width : VTMN_DEFAULT_WIDTH;`
Can you please apply this change? Thanks.

2022-09-01 14:08 UTC, lauthieb requested changes

2022-09-01 14:08 UTC, lauthieb commented on packages/sources/svelte/src/components/structure/VtmnSkeleton/VtmnSkeleton.svelte
> +    VTMN_DEFAULT_DEFAULT__WIDTH,
To rename `VTMN_SKELETON_DEFAULT_WIDTH`
+ add `VTMN_SKELETON_DEFAULT_UNIT`

2022-09-01 14:08 UTC, lauthieb commented on packages/sources/svelte/src/components/structure/VtmnSkeleton/VtmnSkeleton.svelte
> +      computedWidth = 100;
Please use `VTMN_SKELETON_DEFAULT_WIDTH`

2022-09-01 14:08 UTC, lauthieb commented on packages/sources/svelte/src/components/structure/VtmnSkeleton/VtmnSkeleton.svelte
> +      computedUnit = VTMN_SKELETON_UNIT.PERCENT;
Please use `VTMN_SKELETON_DEFAULT_UNIT`

2022-09-01 19:38 UTC, lauthieb submitted a review, later dismissed
That's ok for me, thanks @Tlahey

2022-09-02 06:54 UTC, lauthieb approved these changes

2022-09-02 06:54 UTC, thibault-mahe approved these changes

2022-09-02 13:54 UTC, merged