feat: add topaction right on vtmncard component. introduction of with…
Decathlon/vitamin-web pull request #1348
Opened 2023-01-29 06:43 UTC by AKLEIN26

## Changes description
Introduction of the class 'without-image' to remove the rendering of the image
Introduction of the 'topActions' prop and component
Implementation of two CSS classes for 'topActions'
Update of Storybook by adding the 'topActions' component inside.
Update of engine restriction version to be compatible with 18

## Context
In Singapore we are using a custom component that introduce the topActions for the card 
<img width="1104" alt="CleanShot 2023-01-29 at 14 41 48@2x" src="https://user-images.githubusercontent.com/61679337/215309749-5e4076a2-ed0a-4b98-aa10-93a384e47a08.png">
## Does this introduce a breaking change?
- No

2023-01-29 06:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Decathlon/vitamin-web?pullRequest=1348) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Decathlon/vitamin-web?pullRequest=1348) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Decathlon/vitamin-web?pullRequest=1348) it.</sub>

2023-01-29 06:46 UTC, AKLEIN26 commented on packages/sources/css/src/components/structure/card/src/index.css
> +
Following figma design for the margin settings

2023-01-29 06:47 UTC, AKLEIN26 commented on packages/sources/react/src/components/structure/VtmnCard/VtmnCard.tsx
> -          className,
Separating vtmn-card and variant to use the vtmn-card css. Removing container as no css is apply to it.

2023-01-30 08:36 UTC, lauthieb commented
Hi @AKLEIN26,

Thanks a lot for your proposition.
Unfortunately, when I check on Figma, we don't have any "top actions" for this variant of the `Card` without image:

That's why I suggest you create an issue on vitamin-design: https://github.com/Decathlon/vitamin-design/issues/new/choose. So it can be analyzed and potentially implemented by Vitamin's design team on all the platforms we support (web, android, iOS).

In the meantime, I'll convert your issue into a draft.

Thanks for your contribution.

2023-01-30 08:37 UTC, lauthieb requested changes
Hi @AKLEIN26,

Thanks a lot for your proposition.
Unfortunately, when I check on Figma, we don't have any "top actions" for this variant of the `Card` without image:

<img width="1438" alt="CleanShot 2023-01-30 at 09 37 05@2x" src="https://user-images.githubusercontent.com/9600228/215427476-7f4dabef-d10f-4f68-9bab-0fa9157eb295.png">

That's why I suggest you create an issue on vitamin-design: https://github.com/Decathlon/vitamin-design/issues/new/choose. So it can be analyzed and potentially implemented by Vitamin's design team on all the platforms we support (web, android, iOS).

In the meantime, I'll convert your issue into a draft.

Thanks for your contribution.

2023-02-06 15:14 UTC, lauthieb commented
Hello @AKLEIN26, as discussed together, and [here](https://github.com/Decathlon/vitamin-web/pull/1348#pullrequestreview-1274682509), feel free to open an issue on our other repository https://github.com/decathlon/vitamin-web.
I close this issue, this will delete your branch but no worries, we will be able to restore it if your issue arrives on vitamin-web after his way on vitamin-design.
Thanks again.
Laurent

2023-02-06 15:14 UTC, closed without merging