feat(`@vtmn/react`, `@vtmn/vue`): timeout enhancement
Decathlon/vitamin-web pull request #1483
Opened 2024-02-15 15:41 UTC by Tlahey

## Changes description
Refer to https://github.com/Decathlon/vitamin-web/issues/1482

## Context
Enhancement of the timeout, it is now possible to set a timeout form 0 to Infinity

Update the `VtmnAlert` / `VtmnSnackbar` / `VtmnToast` on React / Vue in order to match the Svelte logic.
Also update the storybook.

## Checklist

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch**. Please, don't request directly from your main!
- [x] Check commits & PR names matches our requested structure. It must follow the https://www.conventionalcommits.org pattern.
- [x] Check your code additions will fail neither code linting checks.
- [x] I have reviewed the submitted code.
- [x] I have tested on related showcases.
- [x] If it includes design changes, please ask for a review `design-system-core-team-design` GitHub team.

## Does this introduce a breaking change?

- No

## Other information

2024-02-20 21:35 UTC, lauthieb requested changes
Thanks a lot @Tlahey for this contrib!
For me it seems to be ok with just few changes suggestions. I'll wait for @thibault-mahe's review to be sure / for double-checking 👀

2024-02-20 21:35 UTC, lauthieb commented on packages/showcases/vue/stories/components/overlays/VtmnSnackbar/VtmnSnackbar.stories.js
> +    },
You don't need to add this, and use the one from the CSF file instead.

2024-02-20 21:35 UTC, lauthieb commented on packages/showcases/vue/stories/components/overlays/VtmnToast/VtmnToast.stories.js
> +    },
Same here.
You don't need to add this, and use the one from the CSF file instead.

2024-02-21 07:32 UTC, thibault-mahe approved these changes

2024-02-21 08:24 UTC, Tlahey commented
Thanks @lauthieb & @thibault-mahe 
I've done the changes + more clean on the component on another commit on the PR
Let me know ^^

2024-02-21 12:50 UTC, lauthieb approved these changes

2024-02-21 12:51 UTC, merged