Refactor/tailwind config
Decathlon/vitamin-web pull request #240
Opened 2021-03-23 21:05 UTC by mgrisole

## Pull Request checklist

🚨 Please review the [guidelines for contributing](../blob/main/CONTRIBUTING.md) to this repository.

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch**. Don't request your main!
- [x] Make sure you are making a pull request against the **main branch** (left side).
- [x] Check the commit's or even all commits' message styles matches our requested structure.
- [x] Check your code additions will fail neither code linting checks nor unit test.

## Description

This PR aims to provide a shorten version of vtmn screens prefixes as long as a new screen scope for mobile only styles.

## Does this introduce a breaking change?

Yes

As this PR change the existing screen names we would need to rename them everywhere they are being used.

- tablet = tb
- small desktop = sd
- medium-desktop = md
- large-desktop = ld

## Other information

❤️ Thank you!

2021-03-23 21:05 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Decathlon/vitamin-web?pullRequest=240) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Decathlon/vitamin-web?pullRequest=240) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Decathlon/vitamin-web?pullRequest=240) it.</sub>

2021-03-24 08:48 UTC, lauthieb requested changes
Thank you @mgrisole for this contribution!
I understand why it's easier to have two letters screen names.
As we already have consumers and don't want to make a breaking change version juste for this,can you just add them in addition without deleting the old ones? Thanks

2021-03-24 12:54 UTC, mgrisole commented
Hi, @lauthieb, I reverted the renaming on existing prefixes.

2021-03-24 16:06 UTC, mgrisole reviewed
Hi, @lauthieb, I reverted the renaming on existing prefixes.

2021-03-31 16:48 UTC, lauthieb approved these changes

2021-03-31 16:49 UTC, merged