feat(@vtmn/css): add select component
Decathlon/vitamin-web pull request #451
Opened 2021-07-19 10:16 UTC by GaspardMathon

## Pull Request checklist

🚨 Please review the [guidelines for contributing](../blob/main/CONTRIBUTING.md) to this repository.

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch**. Don't request your main!
- [ ] Check the commit's or even all commits' message styles matches our requested structure.
- [ ] Check your code additions will fail neither code linting checks nor unit test.
- [ ] Check PR name, it must follow the following pattern : TYPE(@vtmn/PACKAGENAME): SHORT DESCRIPTION

## Description

- Add select component

## Does this introduce a breaking change?

- No

❤️ Thank you!

2021-07-20 12:13 UTC, xavhan approved these changes

2021-07-22 14:07 UTC, lauthieb requested changes

2021-07-22 14:07 UTC, lauthieb commented on packages/showcases/css/stories/components/select/examples/disabled.html
> +        <option value="">Select</option>
Use `<option value="" disabled selected>Select your option</option>` instead.

2021-07-22 14:15 UTC, lauthieb requested changes

2021-07-22 14:15 UTC, lauthieb commented on packages/showcases/css/stories/components/select/examples/disabled.html
> +      <label for="my-select">Label</label>
Please don't reverse `label` and `select` HTML tags. Plus, we don't need an extra `div` incapsulated.

2021-07-23 12:18 UTC, GaspardMathon commented on packages/showcases/css/stories/components/select/examples/disabled.html
> +        <option value="">Select</option>
Done

2021-07-23 14:19 UTC, lauthieb approved these changes

2021-07-23 14:42 UTC, merged