feat(@vtmn/css-toast): add toast component beta
Decathlon/vitamin-web pull request #500
Opened 2021-08-09 13:59 UTC by GaspardMathon

## Pull Request checklist

🚨 Please review the [guidelines for contributing](../blob/main/CONTRIBUTING.md) to this repository.

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch**. Don't request your main!
- [ ] Check the commit's or even all commits' message styles matches our requested structure.
- [ ] Check your code additions will fail neither code linting checks nor unit test.
- [ ] Check PR name, it must follow the https://www.conventionalcommits.org pattern
- [ ] If it's a new component in CSS, ask for design review

## Description

Please describe your Pull Request.

## Does this introduce a breaking change?

- Yes
- No

## Other information

❤️ Thank you!

2021-08-10 11:37 UTC, xavhan commented
I removed the frontend-community review as PR is not ready yet

2021-08-11 13:40 UTC, xavhan commented on packages/sources/css/src/components/toast/src/index.css
> +.vtmn-toast > p {
any particular reason to force the content to be in a p ?

2021-08-11 14:52 UTC, lauthieb requested changes

2021-08-11 14:52 UTC, lauthieb commented on packages/showcases/css/stories/components/toast/examples/overview.html
> +  <div class="vtmn-toast vtmn-toast_icon-info">
```suggestion
  <div class="vtmn-toast vtmn-toast_with-icon-info">
```

2021-08-11 14:52 UTC, lauthieb commented on packages/showcases/css/stories/components/toast/examples/overview.html
> +  <div class="vtmn-toast vtmn-toast_icon-info vtmn-toast_icon-close">
```suggestion
  <div class="vtmn-toast vtmn-toast_with-icon-info vtmn-toast_icon-close">
```

2021-08-11 14:52 UTC, lauthieb commented on packages/sources/css/src/components/toast/src/index.css
> +.vtmn-toast_icon-info > p::before {
```suggestion
.vtmn-toast_with-icon-info > p::before {
```

2021-09-17 12:57 UTC, lauthieb approved these changes
GREAT JOB :tada:

https://media1.giphy.com/media/3o6Ei00MRU2WnGpcGI/giphy.gif?cid=5a38a5a2lm2x5z6fmlsughl2s177e83lx01c4isg8ixihtqt&rid=giphy.gif&ct=g

2021-09-17 13:07 UTC, merged