feat(popover): add svelte component over popover
Decathlon/vitamin-web pull request #552
Opened 2021-08-30 16:56 UTC by mlefebvre-decathlon

## Pull Request checklist

🚨 Please review the [guidelines for contributing](../blob/main/CONTRIBUTING.md) to this repository.

- [*] Make sure you are requesting to **pull a topic/feature/bugfix branch**. Don't request your main!
- [*] Check the commit's or even all commits' message styles matches our requested structure.
- [*] Check your code additions will fail neither code linting checks nor unit test.
- [*] Check PR name, it must follow the https://www.conventionalcommits.org pattern
- [ ] If it's a new component in CSS, ask for design review

## Description

I added : 
- a Svelte component over the `popover` vitamin design :) 
- its stories
- a `classnames` utils, a first step to concatenate classNames and removing falsy ones.

I updated current components in order to use this util. 
Please note that it could be useful in other frameworks, such as React.

I took the liberty to add support for Svelte files in prettier, and for the Svelte CSF story format.

## Does this introduce a breaking change?

- No (I don't think so)

2021-08-30 16:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Decathlon/vitamin-web?pullRequest=552) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Decathlon/vitamin-web?pullRequest=552) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Decathlon/vitamin-web?pullRequest=552) it.</sub>

2021-08-31 08:59 UTC, jquinc30 approved these changes

2021-09-02 12:14 UTC, lauthieb approved these changes

2021-09-06 09:01 UTC, GaspardMathon approved these changes

2021-09-07 13:15 UTC, lauthieb requested changes

2021-09-07 13:15 UTC, lauthieb commented on packages/showcases/svelte/package.json
> +    "@storybook/addon-svelte-csf": "^1.1.0"
@mlefebvre-decathlon you can move this in `devDependencies` instead.

2021-09-07 13:15 UTC, lauthieb commented on packages/sources/svelte/src/components/VtmnPopover.svelte
> +  export const DEFAULT_POSITION = POSITION.BOTTOM;
Idea from @jleveugle, an `auto` position by default. I will create an issue for this.

2021-09-10 15:48 UTC, lauthieb commented
@mlefebvre-decathlon thanks again, can you please move your dependency to `devDependencies` as requested? I will merge it just after :)
thanks

2021-09-14 09:30 UTC, lauthieb approved these changes

2021-09-14 20:34 UTC, merged