refactor(@vtmn/react): refacto VtmnTooltipPosition props from enum to…
Decathlon/vitamin-web pull request #748
Opened 2021-11-18 08:37 UTC by AntoineDeloy

… type

## Pull Request checklist

🚨 Please review the [guidelines for contributing](../blob/main/CONTRIBUTING.md) to this repository.

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch**. Don't request your main!
- [ ] Check the commit's or even all commits' message styles matches our requested structure.
- [ ] Check your code additions will fail neither code linting checks nor unit test.
- [ ] Check PR name, it must follow the https://www.conventionalcommits.org pattern
- [ ] If it's a new component in CSS, ask for design review

## Description

Please describe your Pull Request.

## Does this introduce a breaking change?

- No

## Other information

The position of tooltip is now modifiable easily by users because before as it was an enum, developers must create the enum in their local architecture, now it complies with the behaviour if current vtmn react components, the props which must receive certain string values are declared as a Type.

❤️ Thank you!

2021-11-18 13:52 UTC, lauthieb requested changes

2021-11-18 13:52 UTC, lauthieb commented on packages/sources/react/src/components/VtmnTooltip/types.ts
> +  | 'bottom - right'
```suggestion
  | 'bottom-right'
```

2021-11-22 08:25 UTC, lauthieb commented
Thanks Antoine, I will check the problem!

2021-11-22 08:38 UTC, AntoineDeloy commented
@lauthieb I don't understand why the build still fails, do you think in's related to the package.json or something similar ? Cause i did not change anything that could throw an error in showcases and on my local the build is not failing at all

2021-11-22 15:08 UTC, merged