feat(@vtmn/vue): add types and props
Decathlon/vitamin-web pull request #954
Opened 2022-02-03 21:09 UTC by ThomasLaigneauDecathlon

## Changes description

Add type and isDisabled props and better Typescript definition with types.

## Context

## Checklist

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch**. Please, don't request directly from your main!
- [x] Check commits & PR names matches our requested structure. It must follow the https://www.conventionalcommits.org pattern.
- [x] Check your code additions will fail neither code linting checks.
- [x] I have reviewed the submitted code.
- [x] I have tested on related showcases.
- [x] If it includes design changes, please ask for a review with a core team designer.

## Does this introduce a breaking change?

- No

## Other information

We will still need to update VtmnButton component with VtmnIcon when this component will be ready.

2022-02-03 21:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Decathlon/vitamin-web?pullRequest=954) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Decathlon/vitamin-web?pullRequest=954) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Decathlon/vitamin-web?pullRequest=954) it.</sub>

2022-02-07 10:13 UTC, lauthieb requested changes
Thanks a lot @ThomasLaigneauDecathlon, some remarks :)

2022-02-07 10:13 UTC, lauthieb commented on packages/showcases/core/csf/components/actions/button.csf.js
> +  },
Why are you adding this attribute?
We already spread with `v-bind=$attrs` all the different props so I don't understand why we need to add this which is part of HTML Button specification and not Vitamin

2022-02-07 10:13 UTC, lauthieb commented on packages/sources/vue/src/components/VtmnButton/types.ts
> +export type VtmnButtonSize = 'small' | 'medium' | 'large' | 'stretched';
Nice :-)

2022-02-07 10:13 UTC, lauthieb commented on packages/showcases/core/csf/components/actions/button.csf.js
> +  },
Can you please rename it to `disabled` instead of `isDisabled`, we have this convention for all other components :)

2022-02-08 08:50 UTC, GaspardMathon approved these changes

2022-02-08 17:12 UTC, lauthieb approved these changes

2022-02-08 17:12 UTC, merged